// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: alerts.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkAlert = `-- name: CheckAlert :one
SELECT
    id,
    created_at,
    last_occurrence,
    ack_at,
    resolved_at,
    cleared_at,
    device_id,
    ack_by,
    resolved_by,
    alert_metric,
    threshold_id,
    severity,
    state,
    display_message,
    notes
FROM alerts
WHERE
    device_id = $1
    AND alert_metric = $2
    AND state IN ('open', 'acknowledged')
`

type CheckAlertParams struct {
	DeviceID    pgtype.UUID
	AlertMetric string
}

type CheckAlertRow struct {
	ID             pgtype.UUID
	CreatedAt      pgtype.Timestamptz
	LastOccurrence pgtype.Timestamptz
	AckAt          pgtype.Timestamptz
	ResolvedAt     pgtype.Timestamptz
	ClearedAt      pgtype.Timestamptz
	DeviceID       pgtype.UUID
	AckBy          pgtype.UUID
	ResolvedBy     pgtype.UUID
	AlertMetric    string
	ThresholdID    pgtype.UUID
	Severity       SeverityEnum
	State          StateEnum
	DisplayMessage string
	Notes          pgtype.Text
}

func (q *Queries) CheckAlert(ctx context.Context, arg CheckAlertParams) (CheckAlertRow, error) {
	row := q.db.QueryRow(ctx, checkAlert, arg.DeviceID, arg.AlertMetric)
	var i CheckAlertRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.LastOccurrence,
		&i.AckAt,
		&i.ResolvedAt,
		&i.ClearedAt,
		&i.DeviceID,
		&i.AckBy,
		&i.ResolvedBy,
		&i.AlertMetric,
		&i.ThresholdID,
		&i.Severity,
		&i.State,
		&i.DisplayMessage,
		&i.Notes,
	)
	return i, err
}

const clearAlert = `-- name: ClearAlert :exec
UPDATE alerts
SET
    state = 'cleared',
    cleared_at = NOW()
WHERE id = $1
`

func (q *Queries) ClearAlert(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearAlert, id)
	return err
}

const getAlerts = `-- name: GetAlerts :many
SELECT
    devices.id AS device_id,
    devices.nickname,
    alerts.alert_metric,
    alerts.severity,
    alerts.created_at,
    alerts.last_occurrence,
    alerts.id,
    alerts.display_message
FROM alerts
INNER JOIN devices
    ON alerts.device_id = devices.id
WHERE alerts.state IN ('open', 'acknowledged')
ORDER BY
    CASE alerts.severity
        WHEN 'critical' THEN 1
        WHEN 'warning' THEN 2
    END,
    GREATEST(alerts.created_at, alerts.last_occurrence) DESC
`

type GetAlertsRow struct {
	DeviceID       pgtype.UUID
	Nickname       string
	AlertMetric    string
	Severity       SeverityEnum
	CreatedAt      pgtype.Timestamptz
	LastOccurrence pgtype.Timestamptz
	ID             pgtype.UUID
	DisplayMessage string
}

func (q *Queries) GetAlerts(ctx context.Context) ([]GetAlertsRow, error) {
	rows, err := q.db.Query(ctx, getAlerts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAlertsRow
	for rows.Next() {
		var i GetAlertsRow
		if err := rows.Scan(
			&i.DeviceID,
			&i.Nickname,
			&i.AlertMetric,
			&i.Severity,
			&i.CreatedAt,
			&i.LastOccurrence,
			&i.ID,
			&i.DisplayMessage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenExternalAlerts = `-- name: ListOpenExternalAlerts :many
SELECT
    id,
    source,
    source_ref,
    external_device_name,
    alert_metric,
    severity,
    state,
    display_message,
    created_at,
    last_occurrence,
    ack_at
FROM alerts
WHERE
    source != 'internal'
    AND state IN ('open', 'acknowledged')
ORDER BY
    CASE severity WHEN 'critical' THEN 0 ELSE 1 END,
    CASE state WHEN 'open' THEN 0 ELSE 1 END,
    last_occurrence DESC NULLS LAST
LIMIT 50
`

type ListOpenExternalAlertsRow struct {
	ID                 pgtype.UUID
	Source             string
	SourceRef          pgtype.Text
	ExternalDeviceName pgtype.Text
	AlertMetric        string
	Severity           SeverityEnum
	State              StateEnum
	DisplayMessage     string
	CreatedAt          pgtype.Timestamptz
	LastOccurrence     pgtype.Timestamptz
	AckAt              pgtype.Timestamptz
}

func (q *Queries) ListOpenExternalAlerts(ctx context.Context) ([]ListOpenExternalAlertsRow, error) {
	rows, err := q.db.Query(ctx, listOpenExternalAlerts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOpenExternalAlertsRow
	for rows.Next() {
		var i ListOpenExternalAlertsRow
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.SourceRef,
			&i.ExternalDeviceName,
			&i.AlertMetric,
			&i.Severity,
			&i.State,
			&i.DisplayMessage,
			&i.CreatedAt,
			&i.LastOccurrence,
			&i.AckAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAlertLastOccurrence = `-- name: UpdateAlertLastOccurrence :exec
UPDATE alerts
SET
    last_occurrence = NOW(),
    severity = $1
WHERE id = $2
`

type UpdateAlertLastOccurrenceParams struct {
	Severity SeverityEnum
	ID       pgtype.UUID
}

func (q *Queries) UpdateAlertLastOccurrence(ctx context.Context, arg UpdateAlertLastOccurrenceParams) error {
	_, err := q.db.Exec(ctx, updateAlertLastOccurrence, arg.Severity, arg.ID)
	return err
}

const writeAlert = `-- name: WriteAlert :exec
INSERT INTO alerts (
    last_occurrence,
    device_id,
    alert_metric,
    threshold_id,
    severity,
    display_message
) VALUES (
    NOW(),
    $1,
    $2,
    $3,
    $4::severity_enum,
    (
        SELECT
            COALESCE(nickname, hostname, 'unknown-device')
            || ' — ' || $2::text || ' ' || ($4::severity_enum)::text
        FROM devices
        WHERE id = $1
    )
)
`

type WriteAlertParams struct {
	DeviceID    pgtype.UUID
	AlertMetric string
	ThresholdID pgtype.UUID
	Column4     SeverityEnum
}

func (q *Queries) WriteAlert(ctx context.Context, arg WriteAlertParams) error {
	_, err := q.db.Exec(ctx, writeAlert,
		arg.DeviceID,
		arg.AlertMetric,
		arg.ThresholdID,
		arg.Column4,
	)
	return err
}
