// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: alerts.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkAlert = `-- name: CheckAlert :one
SELECT id, created_at, last_occurrence, ack_at, resolved_at, cleared_at, device_id, ack_by, resolved_by, alert_metric, threshold_id, severity, state, notes FROM alerts
WHERE device_id = $1
AND alert_metric = $2
AND state IN ('open', 'acknowledged')
`

type CheckAlertParams struct {
	DeviceID    pgtype.UUID
	AlertMetric string
}

func (q *Queries) CheckAlert(ctx context.Context, arg CheckAlertParams) (Alert, error) {
	row := q.db.QueryRow(ctx, checkAlert, arg.DeviceID, arg.AlertMetric)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.LastOccurrence,
		&i.AckAt,
		&i.ResolvedAt,
		&i.ClearedAt,
		&i.DeviceID,
		&i.AckBy,
		&i.ResolvedBy,
		&i.AlertMetric,
		&i.ThresholdID,
		&i.Severity,
		&i.State,
		&i.Notes,
	)
	return i, err
}

const getAlerts = `-- name: GetAlerts :many
SELECT devices.nickname, alerts.alert_metric, alerts.severity, alerts.created_at, alerts.last_occurrence
FROM alerts
INNER JOIN devices ON alerts.device_id = devices.id
WHERE state IN ('open', 'acknowledged')
ORDER BY 
	CASE severity
		WHEN 'critical' THEN 1
		WHEN 'warning' THEN 2
	END,
	GREATEST(alerts.created_at, alerts.last_occurrence) DESC
`

type GetAlertsRow struct {
	Nickname       string
	AlertMetric    string
	Severity       SeverityEnum
	CreatedAt      pgtype.Timestamptz
	LastOccurrence pgtype.Timestamptz
}

func (q *Queries) GetAlerts(ctx context.Context) ([]GetAlertsRow, error) {
	rows, err := q.db.Query(ctx, getAlerts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAlertsRow
	for rows.Next() {
		var i GetAlertsRow
		if err := rows.Scan(
			&i.Nickname,
			&i.AlertMetric,
			&i.Severity,
			&i.CreatedAt,
			&i.LastOccurrence,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAlertLastOccurrence = `-- name: UpdateAlertLastOccurrence :exec
UPDATE alerts
SET last_occurrence = NOW(), severity = $1
WHERE id = $2
`

type UpdateAlertLastOccurrenceParams struct {
	Severity SeverityEnum
	ID       pgtype.UUID
}

func (q *Queries) UpdateAlertLastOccurrence(ctx context.Context, arg UpdateAlertLastOccurrenceParams) error {
	_, err := q.db.Exec(ctx, updateAlertLastOccurrence, arg.Severity, arg.ID)
	return err
}

const writeAlert = `-- name: WriteAlert :exec
INSERT INTO alerts (
	id,
	last_occurrence,
	device_id,
	alert_metric,
	threshold_id,
	severity
	) VALUES (
	$1,
	NOW(),
	$2,
	$3,
	$4,
	$5
)
`

type WriteAlertParams struct {
	ID          pgtype.UUID
	DeviceID    pgtype.UUID
	AlertMetric string
	ThresholdID pgtype.UUID
	Severity    SeverityEnum
}

func (q *Queries) WriteAlert(ctx context.Context, arg WriteAlertParams) error {
	_, err := q.db.Exec(ctx, writeAlert,
		arg.ID,
		arg.DeviceID,
		arg.AlertMetric,
		arg.ThresholdID,
		arg.Severity,
	)
	return err
}
