// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: auth.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (
  id,
  user_id,
  created_at,
  refresh_at,
  expires_at,
  token_hash
)
VALUES (
  uuid(),
  $1,
  now(),
  now(),
  now() + INTERVAL '1 hour',
  $2
)
`

type CreateSessionParams struct {
	UserID    pgtype.UUID
	TokenHash string
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession, arg.UserID, arg.TokenHash)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions
WHERE token_hash = $1
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, deleteSession, tokenHash)
	return err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT
  id,
  user_id,
  created_at,
  refreshed_at,
  expires_at
FROM sessions
WHERE token_hash = $1
LIMIT 1
`

type GetSessionByTokenHashRow struct {
	ID          pgtype.UUID
	UserID      pgtype.UUID
	CreatedAt   pgtype.Timestamptz
	RefreshedAt pgtype.Timestamptz
	ExpiresAt   pgtype.Timestamptz
}

func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash string) (GetSessionByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getSessionByTokenHash, tokenHash)
	var i GetSessionByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.RefreshedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT
  id,
  first_name,
  last_name,
  role,
  job_title,
  email,
  phone_number,
  password_hash,
  created_at,
  last_login,
  on_call
FROM users
WHERE email = $1
LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Role,
		&i.JobTitle,
		&i.Email,
		&i.PhoneNumber,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.LastLogin,
		&i.OnCall,
	)
	return i, err
}
