// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: devices.sql

package database

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDevice = `-- name: CreateDevice :exec
INSERT INTO devices (
    id,
    nickname,
    hostname,
    ip_address,
    last_seen_at,
    polling_interval,
    serial,
    manufacturer,
    model,
    location,
    room,
    type,
    os,
    notes,
    tags
)
VALUES (
    uuid(),
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14
)
`

type CreateDeviceParams struct {
	Nickname        string
	Hostname        pgtype.Text
	IpAddress       netip.Addr
	LastSeenAt      pgtype.Timestamptz
	PollingInterval pgtype.Interval
	Serial          pgtype.Text
	Manufacturer    pgtype.Text
	Model           pgtype.Text
	Location        string
	Room            pgtype.Text
	Type            string
	Os              pgtype.Text
	Notes           pgtype.Text
	Tags            []byte
}

func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) error {
	_, err := q.db.Exec(ctx, createDevice,
		arg.Nickname,
		arg.Hostname,
		arg.IpAddress,
		arg.LastSeenAt,
		arg.PollingInterval,
		arg.Serial,
		arg.Manufacturer,
		arg.Model,
		arg.Location,
		arg.Room,
		arg.Type,
		arg.Os,
		arg.Notes,
		arg.Tags,
	)
	return err
}

const getDevices = `-- name: GetDevices :many
SELECT
    id,
    created_at,
    nickname,
    hostname,
    ip_address,
    last_seen_at,
    enabled,
    polling_interval,
    serial,
    manufacturer,
    model,
    location,
    room,
    type,
    os,
    notes,
    tags
FROM devices
`

func (q *Queries) GetDevices(ctx context.Context) ([]Device, error) {
	rows, err := q.db.Query(ctx, getDevices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Device
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.Nickname,
			&i.Hostname,
			&i.IpAddress,
			&i.LastSeenAt,
			&i.Enabled,
			&i.PollingInterval,
			&i.Serial,
			&i.Manufacturer,
			&i.Model,
			&i.Location,
			&i.Room,
			&i.Type,
			&i.Os,
			&i.Notes,
			&i.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDevicesOneLocation = `-- name: GetDevicesOneLocation :many
SELECT
    id,
    created_at,
    nickname,
    hostname,
    ip_address,
    last_seen_at,
    enabled,
    polling_interval,
    serial,
    manufacturer,
    model,
    location,
    room,
    type,
    os,
    notes,
    tags
FROM devices
WHERE location = $1
`

func (q *Queries) GetDevicesOneLocation(ctx context.Context, location string) ([]Device, error) {
	rows, err := q.db.Query(ctx, getDevicesOneLocation, location)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Device
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.Nickname,
			&i.Hostname,
			&i.IpAddress,
			&i.LastSeenAt,
			&i.Enabled,
			&i.PollingInterval,
			&i.Serial,
			&i.Manufacturer,
			&i.Model,
			&i.Location,
			&i.Room,
			&i.Type,
			&i.Os,
			&i.Notes,
			&i.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDistinctLocations = `-- name: GetDistinctLocations :many
SELECT DISTINCT location FROM devices
`

func (q *Queries) GetDistinctLocations(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, getDistinctLocations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var location string
		if err := rows.Scan(&location); err != nil {
			return nil, err
		}
		items = append(items, location)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOneDeviceInfo = `-- name: GetOneDeviceInfo :one
SELECT
    id,
    created_at,
    nickname,
    hostname,
    ip_address,
    last_seen_at,
    enabled,
    polling_interval,
    serial,
    manufacturer,
    model,
    location,
    room,
    type,
    os,
    notes,
    tags
FROM devices
WHERE id = $1
`

func (q *Queries) GetOneDeviceInfo(ctx context.Context, id pgtype.UUID) (Device, error) {
	row := q.db.QueryRow(ctx, getOneDeviceInfo, id)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Nickname,
		&i.Hostname,
		&i.IpAddress,
		&i.LastSeenAt,
		&i.Enabled,
		&i.PollingInterval,
		&i.Serial,
		&i.Manufacturer,
		&i.Model,
		&i.Location,
		&i.Room,
		&i.Type,
		&i.Os,
		&i.Notes,
		&i.Tags,
	)
	return i, err
}
