// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: devices.sql

package database

import (
	"context"
)

const getDevices = `-- name: GetDevices :many
SELECT id, created_at, nickname, hostname, ip_address, last_seen_at, enabled, polling_interval, serial, manufacturer, model, location, room, type, os, notes, tags FROM devices
`

func (q *Queries) GetDevices(ctx context.Context) ([]Device, error) {
	rows, err := q.db.Query(ctx, getDevices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Device
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.Nickname,
			&i.Hostname,
			&i.IpAddress,
			&i.LastSeenAt,
			&i.Enabled,
			&i.PollingInterval,
			&i.Serial,
			&i.Manufacturer,
			&i.Model,
			&i.Location,
			&i.Room,
			&i.Type,
			&i.Os,
			&i.Notes,
			&i.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
