// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ext_alerts.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const upsertExternalAlert = `-- name: UpsertExternalAlert :exec
INSERT INTO alerts (
    created_at,
    last_occurrence,
    source,
    source_ref,
    external_device_name,
    alert_metric,
    severity,
    display_message,
    external_raw_json
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
)
ON CONFLICT (source, source_ref) WHERE source_ref IS NOT NULL
DO UPDATE SET
    severity = excluded.severity,
    last_occurrence = excluded.last_occurrence,
    external_device_name = excluded.external_device_name,
    alert_metric = excluded.alert_metric,
    external_raw_json = excluded.external_raw_json,
    display_message = excluded.display_message
`

type UpsertExternalAlertParams struct {
	CreatedAt          pgtype.Timestamptz
	LastOccurrence     pgtype.Timestamptz
	Source             string
	SourceRef          pgtype.Text
	ExternalDeviceName pgtype.Text
	AlertMetric        string
	Severity           SeverityEnum
	DisplayMessage     string
	ExternalRawJson    []byte
}

func (q *Queries) UpsertExternalAlert(ctx context.Context, arg UpsertExternalAlertParams) error {
	_, err := q.db.Exec(ctx, upsertExternalAlert,
		arg.CreatedAt,
		arg.LastOccurrence,
		arg.Source,
		arg.SourceRef,
		arg.ExternalDeviceName,
		arg.AlertMetric,
		arg.Severity,
		arg.DisplayMessage,
		arg.ExternalRawJson,
	)
	return err
}
