// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: metrics.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPacketLossByDeviceID = `-- name: GetPacketLossByDeviceID :one
SELECT metric_name, value, device_id, requested_at, received_at
FROM metrics
WHERE device_id = $1 AND name = 'packet_loss'
ORDER BY requested_at DESC
LIMIT 1
`

func (q *Queries) GetPacketLossByDeviceID(ctx context.Context, deviceID pgtype.UUID) (Metric, error) {
	row := q.db.QueryRow(ctx, getPacketLossByDeviceID, deviceID)
	var i Metric
	err := row.Scan(
		&i.MetricName,
		&i.Value,
		&i.DeviceID,
		&i.RequestedAt,
		&i.ReceivedAt,
	)
	return i, err
}

const getRttAvgByDeviceID = `-- name: GetRttAvgByDeviceID :one
SELECT metric_name, value, device_id, requested_at, received_at
FROM metrics
WHERE device_id = $1 AND name = 'rtt_avg'
ORDER BY requested_at DESC
LIMIT 1
`

func (q *Queries) GetRttAvgByDeviceID(ctx context.Context, deviceID pgtype.UUID) (Metric, error) {
	row := q.db.QueryRow(ctx, getRttAvgByDeviceID, deviceID)
	var i Metric
	err := row.Scan(
		&i.MetricName,
		&i.Value,
		&i.DeviceID,
		&i.RequestedAt,
		&i.ReceivedAt,
	)
	return i, err
}
