// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: metrics.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAllMetricsForOneDeviceByID = `-- name: GetAllMetricsForOneDeviceByID :many
SELECT metric_name, value, device_id, requested_at, received_at
FROM metrics
WHERE device_id = $1
AND requested_at > NOW() - INTERVAL '12 hours'
ORDER BY requested_at DESC
`

func (q *Queries) GetAllMetricsForOneDeviceByID(ctx context.Context, deviceID pgtype.UUID) ([]Metric, error) {
	rows, err := q.db.Query(ctx, getAllMetricsForOneDeviceByID, deviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Metric
	for rows.Next() {
		var i Metric
		if err := rows.Scan(
			&i.MetricName,
			&i.Value,
			&i.DeviceID,
			&i.RequestedAt,
			&i.ReceivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPacketLossByDeviceID = `-- name: GetPacketLossByDeviceID :one
SELECT metric_name, value, device_id, requested_at, received_at
FROM metrics
WHERE device_id = $1 AND metric_name = 'packet_loss'
ORDER BY requested_at DESC
LIMIT 1
`

func (q *Queries) GetPacketLossByDeviceID(ctx context.Context, deviceID pgtype.UUID) (Metric, error) {
	row := q.db.QueryRow(ctx, getPacketLossByDeviceID, deviceID)
	var i Metric
	err := row.Scan(
		&i.MetricName,
		&i.Value,
		&i.DeviceID,
		&i.RequestedAt,
		&i.ReceivedAt,
	)
	return i, err
}

const getRttAvgByDeviceID = `-- name: GetRttAvgByDeviceID :one
SELECT metric_name, value, device_id, requested_at, received_at
FROM metrics
WHERE device_id = $1 AND metric_name = 'rtt_avg'
ORDER BY requested_at DESC
LIMIT 1
`

func (q *Queries) GetRttAvgByDeviceID(ctx context.Context, deviceID pgtype.UUID) (Metric, error) {
	row := q.db.QueryRow(ctx, getRttAvgByDeviceID, deviceID)
	var i Metric
	err := row.Scan(
		&i.MetricName,
		&i.Value,
		&i.DeviceID,
		&i.RequestedAt,
		&i.ReceivedAt,
	)
	return i, err
}
