// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql/driver"
	"fmt"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type DirectionEnum string

const (
	DirectionEnumAbove DirectionEnum = "above"
	DirectionEnumBelow DirectionEnum = "below"
	DirectionEnumBoth  DirectionEnum = "both"
)

func (e *DirectionEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DirectionEnum(s)
	case string:
		*e = DirectionEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for DirectionEnum: %T", src)
	}
	return nil
}

type NullDirectionEnum struct {
	DirectionEnum DirectionEnum
	Valid         bool // Valid is true if DirectionEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDirectionEnum) Scan(value interface{}) error {
	if value == nil {
		ns.DirectionEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DirectionEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDirectionEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DirectionEnum), nil
}

type ErrorType string

const (
	ErrorTypeDns          ErrorType = "dns"
	ErrorTypeUnreachable  ErrorType = "unreachable"
	ErrorTypeUnauthorized ErrorType = "unauthorized"
	ErrorTypeCollector    ErrorType = "collector"
	ErrorTypeSaasOutage   ErrorType = "saas_outage"
	ErrorTypeIsp          ErrorType = "isp"
)

func (e *ErrorType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ErrorType(s)
	case string:
		*e = ErrorType(s)
	default:
		return fmt.Errorf("unsupported scan type for ErrorType: %T", src)
	}
	return nil
}

type NullErrorType struct {
	ErrorType ErrorType
	Valid     bool // Valid is true if ErrorType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullErrorType) Scan(value interface{}) error {
	if value == nil {
		ns.ErrorType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ErrorType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullErrorType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ErrorType), nil
}

type RolesEnum string

const (
	RolesEnumAdministrator RolesEnum = "administrator"
	RolesEnumEditor        RolesEnum = "editor"
	RolesEnumReadOnly      RolesEnum = "read-only"
)

func (e *RolesEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RolesEnum(s)
	case string:
		*e = RolesEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for RolesEnum: %T", src)
	}
	return nil
}

type NullRolesEnum struct {
	RolesEnum RolesEnum
	Valid     bool // Valid is true if RolesEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRolesEnum) Scan(value interface{}) error {
	if value == nil {
		ns.RolesEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RolesEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRolesEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RolesEnum), nil
}

type SeverityEnum string

const (
	SeverityEnumWarning  SeverityEnum = "warning"
	SeverityEnumCritical SeverityEnum = "critical"
)

func (e *SeverityEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SeverityEnum(s)
	case string:
		*e = SeverityEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for SeverityEnum: %T", src)
	}
	return nil
}

type NullSeverityEnum struct {
	SeverityEnum SeverityEnum
	Valid        bool // Valid is true if SeverityEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSeverityEnum) Scan(value interface{}) error {
	if value == nil {
		ns.SeverityEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SeverityEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSeverityEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SeverityEnum), nil
}

type StateEnum string

const (
	StateEnumOpen         StateEnum = "open"
	StateEnumAcknowledged StateEnum = "acknowledged"
	StateEnumResolved     StateEnum = "resolved"
	StateEnumCleared      StateEnum = "cleared"
)

func (e *StateEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = StateEnum(s)
	case string:
		*e = StateEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for StateEnum: %T", src)
	}
	return nil
}

type NullStateEnum struct {
	StateEnum StateEnum
	Valid     bool // Valid is true if StateEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStateEnum) Scan(value interface{}) error {
	if value == nil {
		ns.StateEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.StateEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStateEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.StateEnum), nil
}

type Alert struct {
	ID                 pgtype.UUID
	CreatedAt          pgtype.Timestamptz
	LastOccurrence     pgtype.Timestamptz
	AckAt              pgtype.Timestamptz
	ResolvedAt         pgtype.Timestamptz
	ClearedAt          pgtype.Timestamptz
	DeviceID           pgtype.UUID
	AckBy              pgtype.UUID
	ResolvedBy         pgtype.UUID
	AlertMetric        string
	ThresholdID        pgtype.UUID
	Severity           SeverityEnum
	State              StateEnum
	Notes              pgtype.Text
	Source             string
	SourceRef          pgtype.Text
	ExternalDeviceName pgtype.Text
	ExternalRawJson    []byte
	DisplayMessage     string
}

type CollectionError struct {
	DeviceID     pgtype.UUID
	RequestedAt  pgtype.Timestamptz
	MetricName   string
	Type         ErrorType
	ErrorMessage string
	Retries      int32
	RawResponse  []byte
}

type Device struct {
	ID              pgtype.UUID
	CreatedAt       pgtype.Timestamptz
	Nickname        string
	Hostname        pgtype.Text
	IpAddress       netip.Addr
	LastSeenAt      pgtype.Timestamptz
	Enabled         bool
	PollingInterval pgtype.Interval
	Serial          pgtype.Text
	Manufacturer    pgtype.Text
	Model           pgtype.Text
	Location        string
	Room            pgtype.Text
	Type            string
	Os              pgtype.Text
	Notes           pgtype.Text
	Tags            []byte
}

type DevicesProtocol struct {
	DeviceID       pgtype.UUID
	ProtocolID     pgtype.UUID
	Enabled        bool
	AssignedAt     pgtype.Timestamptz
	Port           int32
	PollingRate    pgtype.Interval
	Encryption     pgtype.Bool
	VaultReference pgtype.Text
}

type Metric struct {
	MetricName  string
	Value       float64
	DeviceID    pgtype.UUID
	RequestedAt pgtype.Timestamptz
	ReceivedAt  pgtype.Timestamptz
}

type Protocol struct {
	ID        pgtype.UUID
	Name      string
	CreatedAt pgtype.Timestamptz
}

type Session struct {
	ID          pgtype.UUID
	UserID      pgtype.UUID
	CreatedAt   pgtype.Timestamptz
	RefreshedAt pgtype.Timestamptz
	ExpiresAt   pgtype.Timestamptz
	TokenHash   string
}

type Threshold struct {
	ID            pgtype.UUID
	DeviceID      pgtype.UUID
	DeviceType    pgtype.Text
	Metric        string
	WarningValue  float64
	CriticalValue float64
	Direction     DirectionEnum
	CreatedAt     pgtype.Timestamptz
	ModifiedAt    pgtype.Timestamptz
}

type User struct {
	ID           pgtype.UUID
	FirstName    string
	LastName     string
	Role         RolesEnum
	JobTitle     pgtype.Text
	Email        string
	PhoneNumber  string
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
	LastLogin    pgtype.Timestamptz
	OnCall       bool
}
