// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ping.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const writePing = `-- name: WritePing :exec
INSERT INTO metrics (metric_name, value, device_id, requested_at, received_at)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
),
(
    $6,
    $7,
    $8,
    $9,
    $10
)
`

type WritePingParams struct {
	MetricName    string
	Value         float64
	DeviceID      pgtype.UUID
	RequestedAt   pgtype.Timestamptz
	ReceivedAt    pgtype.Timestamptz
	MetricName_2  string
	Value_2       float64
	DeviceID_2    pgtype.UUID
	RequestedAt_2 pgtype.Timestamptz
	ReceivedAt_2  pgtype.Timestamptz
}

func (q *Queries) WritePing(ctx context.Context, arg WritePingParams) error {
	_, err := q.db.Exec(ctx, writePing,
		arg.MetricName,
		arg.Value,
		arg.DeviceID,
		arg.RequestedAt,
		arg.ReceivedAt,
		arg.MetricName_2,
		arg.Value_2,
		arg.DeviceID_2,
		arg.RequestedAt_2,
		arg.ReceivedAt_2,
	)
	return err
}
