// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: ping.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const writePing = `-- name: WritePing :exec
INSERT INTO metrics (metric_name, value, device_id, requested_at, received_at)
VALUES (
	$1,
	$2,
	$3,
	$4,
	$5
	)
`

type WritePingParams struct {
	MetricName  string
	Value       float64
	DeviceID    pgtype.UUID
	RequestedAt pgtype.Timestamptz
	ReceivedAt  pgtype.Timestamptz
}

func (q *Queries) WritePing(ctx context.Context, arg WritePingParams) error {
	_, err := q.db.Exec(ctx, writePing,
		arg.MetricName,
		arg.Value,
		arg.DeviceID,
		arg.RequestedAt,
		arg.ReceivedAt,
	)
	return err
}
