// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: protocols_devices.sql

package database

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const getIPandTypefromDeviceID = `-- name: GetIPandTypefromDeviceID :one
SELECT ip_address, type FROM devices WHERE id = $1
`

type GetIPandTypefromDeviceIDRow struct {
	IpAddress netip.Addr
	Type      string
}

func (q *Queries) GetIPandTypefromDeviceID(ctx context.Context, id pgtype.UUID) (GetIPandTypefromDeviceIDRow, error) {
	row := q.db.QueryRow(ctx, getIPandTypefromDeviceID, id)
	var i GetIPandTypefromDeviceIDRow
	err := row.Scan(&i.IpAddress, &i.Type)
	return i, err
}

const getIPfromDeviceID = `-- name: GetIPfromDeviceID :one
SELECT ip_address FROM devices WHERE id = $1
`

func (q *Queries) GetIPfromDeviceID(ctx context.Context, id pgtype.UUID) (netip.Addr, error) {
	row := q.db.QueryRow(ctx, getIPfromDeviceID, id)
	var ip_address netip.Addr
	err := row.Scan(&ip_address)
	return ip_address, err
}

const getProtocolsDevices = `-- name: GetProtocolsDevices :many
SELECT device_id, protocol_id, enabled, assigned_at, port, polling_rate, encryption, vault_reference FROM devices_protocols
`

func (q *Queries) GetProtocolsDevices(ctx context.Context) ([]DevicesProtocol, error) {
	rows, err := q.db.Query(ctx, getProtocolsDevices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DevicesProtocol
	for rows.Next() {
		var i DevicesProtocol
		if err := rows.Scan(
			&i.DeviceID,
			&i.ProtocolID,
			&i.Enabled,
			&i.AssignedAt,
			&i.Port,
			&i.PollingRate,
			&i.Encryption,
			&i.VaultReference,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
