// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: thresholds.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getActiveThreshold = `-- name: GetActiveThreshold :one
SELECT id, device_id, device_type, metric, warning_value, critical_value, direction, created_at, modified_at FROM thresholds
WHERE metric = $1
AND (device_id = $2 OR device_type = $3 OR (device_id IS NULL AND device_type IS NULL))
ORDER BY
  CASE
    WHEN device_id IS NOT NULL THEN 1
    WHEN device_type IS NOT NULL THEN 2
    ELSE 3
  END
LIMIT 1
`

type GetActiveThresholdParams struct {
	Metric     string
	DeviceID   pgtype.UUID
	DeviceType pgtype.Text
}

func (q *Queries) GetActiveThreshold(ctx context.Context, arg GetActiveThresholdParams) (Threshold, error) {
	row := q.db.QueryRow(ctx, getActiveThreshold, arg.Metric, arg.DeviceID, arg.DeviceType)
	var i Threshold
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.DeviceType,
		&i.Metric,
		&i.WarningValue,
		&i.CriticalValue,
		&i.Direction,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}
